version: "1.0"
tables:
  chexpert:
    file_path: "chexpert-pyhealth.csv"
    patient_id: "deid_patient_id"
    timestamp: null
    attributes:
    - "path_to_image"
    - "frontal_lateral"
    - "ap_pa"
    - "patient_report_date_order"
    - "age"
    - "sex"
    - "race"
    - "ethnicity"
    - "interpreter_needed"
    - "insurance_type"
    - "recent_bmi"
    - "deceased"
    - "split"
    - "section_findings"
    - "section_impression"
    - "report"
