version: "1.0"
tables:
  radiology_reports:
    file_path: "rexkg-chexpert-pyhealth.csv"
    patient_id: "patient_id"
    timestamp: null
    attributes:
      - "study_id"
      - "report_id"
      - "text"
      - "report_type"
      - "path_to_image"
      - "path_to_dcm"
      - "frontal_lateral"
      - "ap_pa"
      - "deid_patient_id"
      - "patient_report_date_order"
      - "report"
      - "section_narrative"
      - "section_clinical_history"
      - "section_history"
      - "section_comparison"
      - "section_technique"
      - "section_procedure_comments"
      - "section_findings"
      - "section_impression"
      - "section_end_of_impression"
      - "section_summary"
      - "section_accession_number"
      - "age"
      - "sex"
      - "race"
      - "ethnicity"
      - "interpreter_needed"
      - "insurance_type"
      - "recent_bmi"
      - "deceased"
      - "split"
