name: cs598-pyhealth
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.13
  - pip
  - ipykernel
  - jupyterlab
  - setuptools
  - wheel
  - pip:
      - -e ./PyHealth
